# Generated by Django 4.1.3 on 2023-01-29 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=96)),
                ('surname', models.CharField(blank=True, max_length=96)),
                ('phone_number', models.CharField(blank=True, max_length=96)),
                ('languages', models.CharField(blank=True, max_length=96)),
                ('job_title', models.CharField(blank=True, max_length=96)),
                ('work_experience', models.CharField(blank=True, max_length=4)),
                ('birth_year', models.CharField(blank=True, max_length=4)),
                ('country', models.CharField(blank=True, max_length=96)),
                ('city', models.CharField(blank=True, max_length=96)),
                ('profile_description', models.TextField(blank=True, max_length=5000)),
                ('fb_link', models.CharField(blank=True, max_length=96)),
                ('twitter_link', models.CharField(blank=True, max_length=96)),
                ('linkedin_link', models.CharField(blank=True, max_length=96)),
                ('instagram_link', models.CharField(blank=True, max_length=96)),
                ('youtube_link', models.CharField(blank=True, max_length=96)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('work_experience', models.CharField(blank=True, max_length=4)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ShortSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=200, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('position_name', models.CharField(blank=True, max_length=200, null=True)),
                ('job_description', models.CharField(blank=True, max_length=200, null=True)),
                ('from_date', models.CharField(blank=True, max_length=15, null=True)),
                ('to_date', models.CharField(blank=True, max_length=15, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=96)),
                ('logo', models.ImageField(default='company_logo/defoult_logo.jpg', upload_to='company_logo')),
                ('banner', models.ImageField(default='company_logo/defoult_baner.jpg', upload_to='company_baner')),
                ('address', models.CharField(blank=True, max_length=96)),
                ('foundation_year', models.CharField(blank=True, max_length=96)),
                ('phone_number', models.CharField(blank=True, max_length=96)),
                ('number_of_workers', models.CharField(blank=True, max_length=15)),
                ('contact_email', models.CharField(blank=True, max_length=96)),
                ('website', models.CharField(blank=True, max_length=96)),
                ('fb_link', models.CharField(blank=True, max_length=96)),
                ('twitter_link', models.CharField(blank=True, max_length=96)),
                ('linkedin_link', models.CharField(blank=True, max_length=96)),
                ('instagram_link', models.CharField(blank=True, max_length=96)),
                ('youtube_link', models.CharField(blank=True, max_length=96)),
                ('company_description', models.TextField(blank=True, max_length=5000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoole_name', models.CharField(blank=True, max_length=200, null=True)),
                ('title_name', models.CharField(blank=True, max_length=200, null=True)),
                ('schoole_description', models.CharField(blank=True, max_length=200, null=True)),
                ('from_date', models.CharField(blank=True, max_length=15, null=True)),
                ('to_date', models.CharField(blank=True, max_length=15, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CertificatesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('job_description', models.CharField(blank=True, max_length=200, null=True)),
                ('from_date', models.CharField(blank=True, max_length=15, null=True)),
                ('to_date', models.CharField(blank=True, max_length=15, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.workerprofile')),
            ],
        ),
    ]
