# Generated by Django 4.1.3 on 2023-01-29 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='birth_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='fb_link',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='profile_description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='work_experience',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('work_experience', models.CharField(blank=True, max_length=4)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ShortSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=200, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('position_name', models.CharField(blank=True, max_length=200, null=True)),
                ('job_description', models.CharField(blank=True, max_length=200, null=True)),
                ('from_date', models.CharField(blank=True, max_length=15, null=True)),
                ('to_date', models.CharField(blank=True, max_length=15, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoole_name', models.CharField(blank=True, max_length=200, null=True)),
                ('schoole_description', models.CharField(blank=True, max_length=200, null=True)),
                ('from_date', models.CharField(blank=True, max_length=15, null=True)),
                ('to_date', models.CharField(blank=True, max_length=15, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CertificatesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('job_description', models.CharField(blank=True, max_length=200, null=True)),
                ('from_date', models.CharField(blank=True, max_length=15, null=True)),
                ('to_date', models.CharField(blank=True, max_length=15, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.workerprofile')),
            ],
        ),
    ]
