# Generated by Django 4.1.3 on 2023-01-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_workerprofile_birth_year_workerprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationhistory',
            name='title_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
