# Generated by Django 4.1.3 on 2023-09-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_employerprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='street',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=96),
        ),
    ]
