# Generated by Django 4.1.3 on 2023-09-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_employerprofile_city_employerprofile_street_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerprofile',
            old_name='address',
            new_name='country',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='post_code',
            field=models.CharField(blank=True, max_length=96),
        ),
    ]
