# Generated by Django 4.1.3 on 2023-01-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0002_alter_joboffer_employer'),
        ('accounts', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmployerProfile',
        ),
        migrations.DeleteModel(
            name='WorkerProfile',
        ),
    ]
