# Generated by Django 4.1.3 on 2023-09-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='joboffer',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='Category', to='job_board.joblanguage'),
        ),
    ]
