# Generated by Django 4.1.3 on 2023-09-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0002_joblanguage_joboffer_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='country',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
